"""Insert data

Revision ID: 6c33b02360af
Revises: 71cc56eecfeb
Create Date: 2024-09-07 19:22:26.564621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c33b02360af'
down_revision: Union[str, None] = '71cc56eecfeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            'todos',
            sa.Column('id', sa.Integer),
            sa.Column('task', sa.String),
            sa.Column('done', sa.Boolean)
        ),
        [
            {'id': 1, 'task': 'Task 1: Prepare env', 'done': True},
            {'id': 2, 'task': 'Task 2: Run data migration', 'done': False}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
